language: python
sudo: required
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install ansible
  - python setup.py install

# command to build and run tests
script:
  - ssh-keygen -y -f /home/travis/.ssh/id_rsa > /home/travis/.ssh/id_rsa.pub
  - cat /home/travis/.ssh/id_rsa.pub >> /home/travis/.ssh/authorized_keys
  - ansible-playbook -b -i tests/inventory tests/test.yml --syntax-check
  - ansible-playbook -b -i tests/inventory tests/test.yml --connection=local --extra-vars "force=true version=5.5"
  - ansible-playbook -b -i tests/inventory tests/test.yml --connection=local --extra-vars "force=false version=5.5"
  - >
    mysql --version | grep 5.5 && (echo 'mysql version test: pass' && exit 0) || (echo 'mysql version test: fail' && exit 1)
  - python setup.py test
  - ansible-playbook -b -i tests/inventory tests/test.yml --connection=local --extra-vars "force=true version=5.6"
  - ansible-playbook -b -i tests/inventory tests/test.yml --connection=local --extra-vars "force=false version=5.6"
  - >
    mysql --version | grep 5.6 && (echo 'mysql version test: pass' && exit 0) || (echo 'mysql version test: fail' && exit 1)
  - python setup.py test
  - ansible-playbook -b -i tests/inventory tests/test.yml --connection=local --extra-vars "force=true version=5.7"
  - ansible-playbook -b -i tests/inventory tests/test.yml --connection=local --extra-vars "force=false version=5.7"
  - >
    mysql --version | grep 5.7 && (echo 'mysql version test: pass' && exit 0) || (echo 'mysql version test: fail' && exit 1)
  - python setup.py test
