language: python
sudo: required
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install ansible
  - pip install pytest

# Run in parallel for each mysql version being tested
env:
  global:
    - CI_NODE_TOTAL=3
  matrix:
  - MYSQL_VERSION=5.5 CI_NODE_INDEX=0
  - MYSQL_VERSION=5.6 CI_NODE_INDEX=1
  - MYSQL_VERSION=5.7 CI_NODE_INDEX=2

# command to build and run tests
script:
  - pytest --capture=no tests
